// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        (unknown)
// source: quadlek/plugins/infobot/v1/infobot.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value    string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsPlural bool   `protobuf:"varint,3,opt,name=is_plural,json=isPlural,proto3" json:"is_plural,omitempty"`
}

func (x *Fact) Reset() {
	*x = Fact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quadlek_plugins_infobot_v1_infobot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fact) ProtoMessage() {}

func (x *Fact) ProtoReflect() protoreflect.Message {
	mi := &file_quadlek_plugins_infobot_v1_infobot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fact.ProtoReflect.Descriptor instead.
func (*Fact) Descriptor() ([]byte, []int) {
	return file_quadlek_plugins_infobot_v1_infobot_proto_rawDescGZIP(), []int{0}
}

func (x *Fact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Fact) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Fact) GetIsPlural() bool {
	if x != nil {
		return x.IsPlural
	}
	return false
}

type FactStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Facts map[string]*Fact `protobuf:"bytes,1,rep,name=facts,proto3" json:"facts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *FactStore) Reset() {
	*x = FactStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quadlek_plugins_infobot_v1_infobot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactStore) ProtoMessage() {}

func (x *FactStore) ProtoReflect() protoreflect.Message {
	mi := &file_quadlek_plugins_infobot_v1_infobot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactStore.ProtoReflect.Descriptor instead.
func (*FactStore) Descriptor() ([]byte, []int) {
	return file_quadlek_plugins_infobot_v1_infobot_proto_rawDescGZIP(), []int{1}
}

func (x *FactStore) GetFacts() map[string]*Fact {
	if x != nil {
		return x.Facts
	}
	return nil
}

var File_quadlek_plugins_infobot_v1_infobot_proto protoreflect.FileDescriptor

var file_quadlek_plugins_infobot_v1_infobot_proto_rawDesc = []byte{
	0x0a, 0x28, 0x71, 0x75, 0x61, 0x64, 0x6c, 0x65, 0x6b, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x73, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x62, 0x6f, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x66,
	0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x71, 0x75, 0x61, 0x64,
	0x6c, 0x65, 0x6b, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x69, 0x6e, 0x66, 0x6f,
	0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x22, 0x4d, 0x0a, 0x04, 0x46, 0x61, 0x63, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x70,
	0x6c, 0x75, 0x72, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x50,
	0x6c, 0x75, 0x72, 0x61, 0x6c, 0x22, 0xaf, 0x01, 0x0a, 0x09, 0x46, 0x61, 0x63, 0x74, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x12, 0x46, 0x0a, 0x05, 0x66, 0x61, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x30, 0x2e, 0x71, 0x75, 0x61, 0x64, 0x6c, 0x65, 0x6b, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x73, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x61, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x46, 0x61, 0x63, 0x74, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x66, 0x61, 0x63, 0x74, 0x73, 0x1a, 0x5a, 0x0a, 0x0a, 0x46,
	0x61, 0x63, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x71, 0x75, 0x61,
	0x64, 0x6c, 0x65, 0x6b, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x69, 0x6e, 0x66,
	0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x63, 0x74, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x71, 0x75, 0x61,
	0x64, 0x6c, 0x65, 0x6b, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f,
	0x69, 0x6e, 0x66, 0x6f, 0x62, 0x6f, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_quadlek_plugins_infobot_v1_infobot_proto_rawDescOnce sync.Once
	file_quadlek_plugins_infobot_v1_infobot_proto_rawDescData = file_quadlek_plugins_infobot_v1_infobot_proto_rawDesc
)

func file_quadlek_plugins_infobot_v1_infobot_proto_rawDescGZIP() []byte {
	file_quadlek_plugins_infobot_v1_infobot_proto_rawDescOnce.Do(func() {
		file_quadlek_plugins_infobot_v1_infobot_proto_rawDescData = protoimpl.X.CompressGZIP(file_quadlek_plugins_infobot_v1_infobot_proto_rawDescData)
	})
	return file_quadlek_plugins_infobot_v1_infobot_proto_rawDescData
}

var file_quadlek_plugins_infobot_v1_infobot_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_quadlek_plugins_infobot_v1_infobot_proto_goTypes = []interface{}{
	(*Fact)(nil),      // 0: quadlek.plugins.infobot.v1.Fact
	(*FactStore)(nil), // 1: quadlek.plugins.infobot.v1.FactStore
	nil,               // 2: quadlek.plugins.infobot.v1.FactStore.FactsEntry
}
var file_quadlek_plugins_infobot_v1_infobot_proto_depIdxs = []int32{
	2, // 0: quadlek.plugins.infobot.v1.FactStore.facts:type_name -> quadlek.plugins.infobot.v1.FactStore.FactsEntry
	0, // 1: quadlek.plugins.infobot.v1.FactStore.FactsEntry.value:type_name -> quadlek.plugins.infobot.v1.Fact
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_quadlek_plugins_infobot_v1_infobot_proto_init() }
func file_quadlek_plugins_infobot_v1_infobot_proto_init() {
	if File_quadlek_plugins_infobot_v1_infobot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quadlek_plugins_infobot_v1_infobot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quadlek_plugins_infobot_v1_infobot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quadlek_plugins_infobot_v1_infobot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quadlek_plugins_infobot_v1_infobot_proto_goTypes,
		DependencyIndexes: file_quadlek_plugins_infobot_v1_infobot_proto_depIdxs,
		MessageInfos:      file_quadlek_plugins_infobot_v1_infobot_proto_msgTypes,
	}.Build()
	File_quadlek_plugins_infobot_v1_infobot_proto = out.File
	file_quadlek_plugins_infobot_v1_infobot_proto_rawDesc = nil
	file_quadlek_plugins_infobot_v1_infobot_proto_goTypes = nil
	file_quadlek_plugins_infobot_v1_infobot_proto_depIdxs = nil
}
