// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.proto

/*
Package github is a generated protocol buffer package.

It is generated from these files:
	github.proto

It has these top-level messages:
	AuthState
	Token
	AuthToken
*/
package github

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthState struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ResponseUrl string `protobuf:"bytes,3,opt,name=response_url,json=responseUrl" json:"response_url,omitempty"`
	ExpireTime  int64  `protobuf:"varint,4,opt,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
}

func (m *AuthState) Reset()                    { *m = AuthState{} }
func (m *AuthState) String() string            { return proto.CompactTextString(m) }
func (*AuthState) ProtoMessage()               {}
func (*AuthState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthState) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthState) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthState) GetResponseUrl() string {
	if m != nil {
		return m.ResponseUrl
	}
	return ""
}

func (m *AuthState) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

type Token struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	TokenType    string `protobuf:"bytes,2,opt,name=token_type,json=tokenType" json:"token_type,omitempty"`
	RefreshToken string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	ExpiresAt    int64  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt" json:"expires_at,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *Token) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *Token) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type AuthToken struct {
	Token  *Token   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Scopes []string `protobuf:"bytes,2,rep,name=scopes" json:"scopes,omitempty"`
}

func (m *AuthToken) Reset()                    { *m = AuthToken{} }
func (m *AuthToken) String() string            { return proto.CompactTextString(m) }
func (*AuthToken) ProtoMessage()               {}
func (*AuthToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthToken) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *AuthToken) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthState)(nil), "github.AuthState")
	proto.RegisterType((*Token)(nil), "github.Token")
	proto.RegisterType((*AuthToken)(nil), "github.AuthToken")
}

func init() { proto.RegisterFile("github.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x94, 0x06, 0xe5, 0x92, 0x32, 0x78, 0x00, 0x2f, 0x88, 0x90, 0x2e, 0x9d, 0x3a,
	0xc0, 0x2f, 0xe8, 0x06, 0x6b, 0x08, 0xb3, 0x95, 0x26, 0x07, 0xb1, 0x68, 0x6b, 0xcb, 0xbe, 0x48,
	0xed, 0x8f, 0xe0, 0x3f, 0xa3, 0xf8, 0x0c, 0x8c, 0xef, 0x7b, 0xa7, 0x77, 0x4f, 0x0f, 0xca, 0x4f,
	0x4d, 0xe3, 0xb4, 0xdf, 0x5a, 0x67, 0xc8, 0x88, 0x8c, 0x55, 0x7d, 0x86, 0x7c, 0x37, 0xd1, 0xf8,
	0x46, 0x1d, 0xa1, 0xb8, 0x81, 0x54, 0x0f, 0x32, 0xa9, 0x92, 0x4d, 0xde, 0xa4, 0x7a, 0x10, 0x77,
	0x70, 0x3d, 0x79, 0x74, 0x4a, 0x0f, 0x32, 0x0d, 0x30, 0x9b, 0xe5, 0xeb, 0x20, 0x1e, 0xa1, 0x74,
	0xe8, 0xad, 0x39, 0x79, 0x54, 0x93, 0x3b, 0xc8, 0x45, 0x70, 0x8b, 0x5f, 0xf6, 0xee, 0x0e, 0xe2,
	0x01, 0x0a, 0x3c, 0x5b, 0xed, 0x50, 0x91, 0x3e, 0xa2, 0xbc, 0xaa, 0x92, 0xcd, 0xa2, 0x01, 0x46,
	0xad, 0x3e, 0x62, 0xfd, 0x9d, 0xc0, 0xb2, 0x35, 0x5f, 0x78, 0x9a, 0xd3, 0xba, 0xbe, 0x47, 0xef,
	0x15, 0xcd, 0x3a, 0x16, 0x28, 0x98, 0xf1, 0xc9, 0x3d, 0x40, 0xf0, 0x14, 0x5d, 0x2c, 0xc6, 0x32,
	0x79, 0x20, 0xed, 0xc5, 0xa2, 0x58, 0xc3, 0xca, 0xe1, 0x87, 0x43, 0x3f, 0xc6, 0x08, 0x2e, 0x54,
	0x46, 0xf8, 0x97, 0xc1, 0xef, 0xbd, 0xea, 0x28, 0x16, 0xca, 0x23, 0xd9, 0x51, 0xfd, 0xc2, 0x4b,
	0xf0, 0xed, 0x1a, 0x96, 0xff, 0x5d, 0x8a, 0xa7, 0xd5, 0x36, 0x8e, 0x17, 0xdc, 0x86, 0x3d, 0x71,
	0x0b, 0x99, 0xef, 0x8d, 0x45, 0x2f, 0xd3, 0x6a, 0x31, 0xaf, 0xc3, 0x6a, 0x9f, 0x85, 0x89, 0x9f,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x04, 0x7c, 0xcb, 0x72, 0x01, 0x00, 0x00,
}
