linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - dogsled
    - durationcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0