FROM lwolf/golang-glide:0.12.3

ENV APP_PATH=/go/src/github.com/jirwin/quadlek
RUN mkdir -p $APP_PATH
ADD . $APP_PATH
WORKDIR $APP_PATH
COPY glide.yaml glide.yaml
COPY glide.lock glide.lock
RUN glide install -v

VOLUME ["/build"]

CMD go build -o /build/quadlekBot