// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        (unknown)
// source: quadlek/plugins/gifs/v1/gifs.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Alias struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phrase  string   `protobuf:"bytes,1,opt,name=phrase,proto3" json:"phrase,omitempty"`
	Allowed []*Reply `protobuf:"bytes,2,rep,name=allowed,proto3" json:"allowed,omitempty"`
	Blocked []*Reply `protobuf:"bytes,3,rep,name=blocked,proto3" json:"blocked,omitempty"`
}

func (x *Alias) Reset() {
	*x = Alias{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quadlek_plugins_gifs_v1_gifs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alias) ProtoMessage() {}

func (x *Alias) ProtoReflect() protoreflect.Message {
	mi := &file_quadlek_plugins_gifs_v1_gifs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alias.ProtoReflect.Descriptor instead.
func (*Alias) Descriptor() ([]byte, []int) {
	return file_quadlek_plugins_gifs_v1_gifs_proto_rawDescGZIP(), []int{0}
}

func (x *Alias) GetPhrase() string {
	if x != nil {
		return x.Phrase
	}
	return ""
}

func (x *Alias) GetAllowed() []*Reply {
	if x != nil {
		return x.Allowed
	}
	return nil
}

func (x *Alias) GetBlocked() []*Reply {
	if x != nil {
		return x.Blocked
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phrase    string `protobuf:"bytes,1,opt,name=phrase,proto3" json:"phrase,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Url       string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quadlek_plugins_gifs_v1_gifs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_quadlek_plugins_gifs_v1_gifs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_quadlek_plugins_gifs_v1_gifs_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetPhrase() string {
	if x != nil {
		return x.Phrase
	}
	return ""
}

func (x *Reply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Reply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_quadlek_plugins_gifs_v1_gifs_proto protoreflect.FileDescriptor

var file_quadlek_plugins_gifs_v1_gifs_proto_rawDesc = []byte{
	0x0a, 0x22, 0x71, 0x75, 0x61, 0x64, 0x6c, 0x65, 0x6b, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x73, 0x2f, 0x67, 0x69, 0x66, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x69, 0x66, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x71, 0x75, 0x61, 0x64, 0x6c, 0x65, 0x6b, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x67, 0x69, 0x66, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x93, 0x01,
	0x0a, 0x05, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x68, 0x72, 0x61, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x12,
	0x38, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x71, 0x75, 0x61, 0x64, 0x6c, 0x65, 0x6b, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x73, 0x2e, 0x67, 0x69, 0x66, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x52, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x12, 0x38, 0x0a, 0x07, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x65, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x71, 0x75, 0x61,
	0x64, 0x6c, 0x65, 0x6b, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x67, 0x69, 0x66,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x22, 0x4f, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x68,
	0x72, 0x61, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x71, 0x75, 0x61, 0x64, 0x6c, 0x65,
	0x6b, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x67, 0x69, 0x66,
	0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quadlek_plugins_gifs_v1_gifs_proto_rawDescOnce sync.Once
	file_quadlek_plugins_gifs_v1_gifs_proto_rawDescData = file_quadlek_plugins_gifs_v1_gifs_proto_rawDesc
)

func file_quadlek_plugins_gifs_v1_gifs_proto_rawDescGZIP() []byte {
	file_quadlek_plugins_gifs_v1_gifs_proto_rawDescOnce.Do(func() {
		file_quadlek_plugins_gifs_v1_gifs_proto_rawDescData = protoimpl.X.CompressGZIP(file_quadlek_plugins_gifs_v1_gifs_proto_rawDescData)
	})
	return file_quadlek_plugins_gifs_v1_gifs_proto_rawDescData
}

var file_quadlek_plugins_gifs_v1_gifs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_quadlek_plugins_gifs_v1_gifs_proto_goTypes = []interface{}{
	(*Alias)(nil), // 0: quadlek.plugins.gifs.v1.Alias
	(*Reply)(nil), // 1: quadlek.plugins.gifs.v1.Reply
}
var file_quadlek_plugins_gifs_v1_gifs_proto_depIdxs = []int32{
	1, // 0: quadlek.plugins.gifs.v1.Alias.allowed:type_name -> quadlek.plugins.gifs.v1.Reply
	1, // 1: quadlek.plugins.gifs.v1.Alias.blocked:type_name -> quadlek.plugins.gifs.v1.Reply
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_quadlek_plugins_gifs_v1_gifs_proto_init() }
func file_quadlek_plugins_gifs_v1_gifs_proto_init() {
	if File_quadlek_plugins_gifs_v1_gifs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quadlek_plugins_gifs_v1_gifs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alias); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quadlek_plugins_gifs_v1_gifs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quadlek_plugins_gifs_v1_gifs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quadlek_plugins_gifs_v1_gifs_proto_goTypes,
		DependencyIndexes: file_quadlek_plugins_gifs_v1_gifs_proto_depIdxs,
		MessageInfos:      file_quadlek_plugins_gifs_v1_gifs_proto_msgTypes,
	}.Build()
	File_quadlek_plugins_gifs_v1_gifs_proto = out.File
	file_quadlek_plugins_gifs_v1_gifs_proto_rawDesc = nil
	file_quadlek_plugins_gifs_v1_gifs_proto_goTypes = nil
	file_quadlek_plugins_gifs_v1_gifs_proto_depIdxs = nil
}
