apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudflared-cert
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  cert.pem: {{ .Values.cloudflared.cert | b64enc | quote }}