apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cloudflared-deployment
  labels:
    app: cloudflared
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: jirwin/cloudflared
        volumeMounts:
          - name: cloudflared-cert
            mountPath: /etc/cloudflared
        env:
        - name: TUNNEL_HOSTNAME
          value: {{ .Values.cloudflared.hostname }}
        - name: TUNNEL_URL
          value: "http://{{ .Release.Name }}-service:8000"
      volumes:
        - name: cloudflared-cert
          secret:
            secretName: {{ .Release.Name }}-cloudflared-cert
