apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: quadlek
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    slack: {{ quote .Values.slackorg }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quadlek
      slack: {{ quote .Values.slackorg }}
  template:
    metadata:
      labels:
        app: quadlek
        slack: {{ quote .Values.slackorg }}
    spec:
      containers:
      - name: quadlek
        image: {{ quote .Values.image }}
        volumeMounts:
          - name: hostpath-volume
            mountPath: /opt
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: api_token
        - name: VERIFICATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: verification_token
        - name: DB_PATH
          value: /opt/quadlek.db
        - name: ENDPOINT
          value: {{ quote .Values.endpoint }}
        - name: GIPHY_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: giphy_key
      volumes:
        - name: hostpath-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-quadlek-pvc
