apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  api_token: {{ .Values.api_token | b64enc | quote }}
  verification_token: {{ .Values.verification_token | b64enc | quote }}
  giphy_key: {{ .Values.giphy_key | b64enc | quote }}