apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ quote .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ quote .Values.service.name }}
  selector:
    app: quadlek