// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package quadlek

import (
	"context"
	"github.com/jirwin/quadlek/pkg/bot"
	"github.com/jirwin/quadlek/pkg/data_store/boltdb"
	"github.com/jirwin/quadlek/pkg/plugin_manager"
	"github.com/jirwin/quadlek/pkg/slack_client"
	"github.com/jirwin/quadlek/pkg/slack_manager"
	"github.com/jirwin/quadlek/pkg/uzap"
	"github.com/jirwin/quadlek/pkg/webhook_manager"
)

// Injectors from wire.go:

func NewQuadlek(ctx context.Context) (Quadlek, error) {
	config, err := bot.NewConfig()
	if err != nil {
		return nil, err
	}
	uzapConfig, err := uzap.NewConfig()
	if err != nil {
		return nil, err
	}
	logger, err := uzap.New(uzapConfig)
	if err != nil {
		return nil, err
	}
	slack_managerConfig, err := slack_manager.NewConfig()
	if err != nil {
		return nil, err
	}
	slack_clientConfig, err := slack_client.NewConfig()
	if err != nil {
		return nil, err
	}
	slackHttpClient := &slack_client.SlackHttpClient{}
	slackClientImpl, err := slack_client.NewSlackClient(slack_clientConfig, logger, slackHttpClient)
	if err != nil {
		return nil, err
	}
	managerImpl, err := slack_manager.New(logger, slack_managerConfig, slackClientImpl)
	if err != nil {
		return nil, err
	}
	plugin_managerConfig, err := plugin_manager.NewConfig()
	if err != nil {
		return nil, err
	}
	webhook_managerConfig, err := webhook_manager.NewConfig()
	if err != nil {
		return nil, err
	}
	webhook_managerManagerImpl, err := webhook_manager.New(webhook_managerConfig, logger, slack_clientConfig)
	if err != nil {
		return nil, err
	}
	boltdbConfig, err := boltdb.NewConfig()
	if err != nil {
		return nil, err
	}
	boltDbStore, err := boltdb.New(boltdbConfig, logger)
	if err != nil {
		return nil, err
	}
	plugin_managerManagerImpl, err := plugin_manager.New(plugin_managerConfig, logger, webhook_managerManagerImpl, managerImpl, boltDbStore)
	if err != nil {
		return nil, err
	}
	quadlekBot, err := bot.New(config, logger, managerImpl, plugin_managerManagerImpl, webhook_managerManagerImpl, boltDbStore)
	if err != nil {
		return nil, err
	}
	return quadlekBot, nil
}
