name: ci

on: push
jobs:
  proto_checks:
    name: proto lint, breaking changes detections
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup buf
        uses: wizhi/setup-buf@v1
        with:
          version: '1.5.0'
      - name: Fetching base branch
        run: |
          git fetch -u origin ${{ github.base_ref }}:${{ github.base_ref }}
      - name: Running linter, checking breaking changes
        run: |
          buf lint
          buf breaking --against ".git#branch=${{ github.base_ref }}"
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: jirwin/quadlek
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}